# https://blog.devgenius.io/colima-a-free-open-source-docker-alternative-for-macos-and-linux-6c5d09ae503e
version: "3.6"
services:
  fileserver:
    image: arm64v8/python 
    restart: always
    ports:
      - '4858:4858'
    volumes:
      -  ./:/hostfiles
    command: sh -c "cd /hostfiles && python3 -m http.server 4858"
  neo4j:
    image: neo4j:5.11.0-community-bullseye
    restart: always
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_server_http_listen__address: 0.0.0.0
      NEO4J_PLUGINS: '["graph-data-science","apoc"]'
  

  

